workflows:
  ios_appstore_ipa:
    name: iOS App Store IPA
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_connect
        - signing
      vars:
        XCODE_PROJECT: "Project-19-12-25-1.xcodeproj"
        XCODE_SCHEME: "Project-19-12-25-1"
        BUNDLE_ID: "ui.temaproger.talkmoney"
        TEAM_ID: "BM58B3Y24D"
        BUILD_NUM: "${CM_BUILD_NUMBER}"
        EXPORT_METHOD: "app-store"

        # ✅ ДОБАВЛЕНО: маркетинговая версия (должна быть > 1.0, иначе "train 1.0 closed")
        APP_VERSION: "1.0.1"

    scripts:
      - name: Show Xcode versions
        script: |
          xcodebuild -version
          swift --version || true

      # ✅ ДОБАВЛЕНО: гарантируем непустой BUILD_NUM для CFBundleVersion
      - name: Set BUILD_NUM (Codemagic built-ins fallback)
        script: |
          set -euo pipefail

          echo "CM_BUILD_NUMBER=${CM_BUILD_NUMBER:-<unset>}"
          echo "BUILD_NUMBER=${BUILD_NUMBER:-<unset>}"
          echo "PROJECT_BUILD_NUMBER=${PROJECT_BUILD_NUMBER:-<unset>}"
          echo "BUILD_NUM(before)=${BUILD_NUM:-<unset>}"

          BUILD_NUM_EFFECTIVE="${CM_BUILD_NUMBER:-${BUILD_NUMBER:-${PROJECT_BUILD_NUMBER:-${BUILD_NUM:-1}}}}"

          echo "Using BUILD_NUM=$BUILD_NUM_EFFECTIVE"
          echo "BUILD_NUM=$BUILD_NUM_EFFECTIVE" >> "$CM_ENV"

      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Install Certificate and Profile from Secrets
        script: |
          # Decode P12 and add to keychain
          echo $CERTIFICATE_P12 | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "$CERTIFICATE_PASSWORD"

          # Decode MobileProvision
          echo $MOBILEPROVISION | base64 --decode > /tmp/profile.mobileprovision
        
          # Copy profile to the correct directory
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        
          # Get the UUID of the profile
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i /tmp/profile.mobileprovision))
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Resolve SPM (optional)
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" || true

      - name: Archive with Smart xcconfig
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          rm -rf "$ARCHIVE_PATH" || true

          # СТРАТЕГИЯ: NO SIGNING AT ARCHIVE
          # Мы собираем архив вообще без подписи.
          # Подпись будет наложена ТОЛЬКО на этапе exportArchive.
          
          # 1. Говорим, что подпись не требуется.
          echo "CODE_SIGNING_REQUIRED = NO" > build.xcconfig
          echo "CODE_SIGNING_ALLOWED = NO" >> build.xcconfig
          
          # 2. Убираем любые упоминания идентичности и профилей.
          echo "CODE_SIGN_IDENTITY = " >> build.xcconfig
          echo "EXPANDED_CODE_SIGN_IDENTITY = " >> build.xcconfig
          echo "PROVISIONING_PROFILE_SPECIFIER = " >> build.xcconfig
          
          # 3. Важно: Устанавливаем команду разработки, чтобы Xcode не ругался на её отсутствие,
          # но подписывать не даем.
          echo "DEVELOPMENT_TEAM = $TEAM_ID" >> build.xcconfig

          # Запускаем архив
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -xcconfig build.xcconfig \
            archive \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            INFOPLIST_KEY_CFBundleVersion="$BUILD_NUM" \
            MARKETING_VERSION="$APP_VERSION" \
            INFOPLIST_KEY_CFBundleShortVersionString="$APP_VERSION" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            CODE_SIGN_STYLE="Manual"

          ls -lah "$CM_BUILD_DIR" || true
          test -d "$ARCHIVE_PATH"

      - name: Verify CFBundleVersion in archive Info.plist
        script: |
          set -euo pipefail
          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          APP_PLIST="$ARCHIVE_PATH/Products/Applications/${XCODE_SCHEME}.app/Info.plist"

          echo "Checking Info.plist:"
          echo "$APP_PLIST"

          echo "CFBundleShortVersionString:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$APP_PLIST" || true

          echo "CFBundleVersion (must exist):"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$APP_PLIST"

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>$EXPORT_METHOD</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROFILE_UUID</string>
              </dict>
          </dict>
          </plist>
          EOF
        
          echo "---- exportOptions.plist ----"
          cat exportOptions.plist

      - name: Export IPA
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          EXPORT_PATH="$CM_EXPORT_DIR"

          mkdir -p "$EXPORT_PATH"

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_PATH"

          ls -lah "$EXPORT_PATH" || true
          test -e "$EXPORT_PATH"/*.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/*.xcarchive
      - exportOptions.plist
